#!/bin/bash
# PreToolUse hook: block Edit/Write on generated/cached paths that the user
# cannot meaningfully edit by hand:
#
#   - dist/                            — regenerated by `tsc` (bun run build)
#   - data/sessions/*/agent-runner-src — per-group cached copy of agent-runner;
#                                        delete (don't edit) to pick up changes
#   - .factory/                        — agent harness scratch dir
#   - node_modules/                    — package manager territory
#
# Edits to these paths are silently lost on the next build/sync, so blocking
# them prevents wasted work and confused debugging sessions.
#
# Exit 2 = block + show stderr to Claude. Exit 0 = allow.

set -u

payload=$(cat)
file_path=$(echo "$payload" | jq -r '.tool_input.file_path // empty')

# Empty file_path? Allow (different tool shape, not our concern).
if [ -z "$file_path" ]; then
  exit 0
fi

# Match against the generated/cached prefixes. Use shell-glob-on-case so we
# catch both absolute and repo-relative forms.
case "$file_path" in
  */nanoclaw/dist/*|dist/*)
    msg="dist/ is regenerated by 'bun run build' from src/. Edit the corresponding src/*.ts file instead."
    ;;
  */nanoclaw/data/sessions/*/agent-runner-src/*|data/sessions/*/agent-runner-src/*)
    msg="data/sessions/{group}/agent-runner-src/ is a per-group cache. Edits are overwritten on next sync. Edit container/agent-runner/src/ instead, then delete the cache to pick up changes."
    ;;
  */nanoclaw/.factory/*|.factory/*)
    msg=".factory/ is agent harness scratch state. Don't edit by hand."
    ;;
  */nanoclaw/node_modules/*|node_modules/*)
    msg="node_modules/ is package manager territory. Edits are blown away on next install. Patch upstream or use a wrapper instead."
    ;;
  *)
    exit 0
    ;;
esac

echo "BLOCKED by protect-generated hook: $file_path" >&2
echo "$msg" >&2
exit 2
